# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainApp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1021, 629)
        Dialog.setMaximumSize(QtCore.QSize(1021, 629))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Globus.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1011, 621))
        self.tabWidget.setMaximumSize(QtCore.QSize(1100, 700))
        self.tabWidget.setToolTipDuration(4)
        self.tabWidget.setObjectName("tabWidget")
        self.Tab1 = QtWidgets.QWidget()
        self.Tab1.setEnabled(True)
        self.Tab1.setObjectName("Tab1")
        self.groupBox = QtWidgets.QGroupBox(self.Tab1)
        self.groupBox.setGeometry(QtCore.QRect(220, 30, 199, 149))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 201, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_GRS = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_GRS.setObjectName("radioButton_GRS")
        self.verticalLayout.addWidget(self.radioButton_GRS)
        self.radioButton_WGS = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_WGS.setObjectName("radioButton_WGS")
        self.verticalLayout.addWidget(self.radioButton_WGS)
        self.label_phi = QtWidgets.QLabel(self.Tab1)
        self.label_phi.setGeometry(QtCore.QRect(50, 220, 201, 31))
        self.label_phi.setObjectName("label_phi")
        self.label_lambda = QtWidgets.QLabel(self.Tab1)
        self.label_lambda.setGeometry(QtCore.QRect(50, 280, 191, 31))
        self.label_lambda.setObjectName("label_lambda")
        self.lineEdit_phi = QtWidgets.QLineEdit(self.Tab1)
        self.lineEdit_phi.setGeometry(QtCore.QRect(260, 230, 141, 20))
        self.lineEdit_phi.setObjectName("lineEdit_phi")
        self.lineEdit_lambda = QtWidgets.QLineEdit(self.Tab1)
        self.lineEdit_lambda.setGeometry(QtCore.QRect(260, 280, 141, 20))
        self.lineEdit_lambda.setObjectName("lineEdit_lambda")
        self.pushButton_92 = QtWidgets.QPushButton(self.Tab1)
        self.pushButton_92.setGeometry(QtCore.QRect(130, 420, 161, 41))
        self.pushButton_92.setObjectName("pushButton_92")
        self.label = QtWidgets.QLabel(self.Tab1)
        self.label.setGeometry(QtCore.QRect(100, 370, 231, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Tab1)
        self.label_2.setGeometry(QtCore.QRect(140, 470, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Tab1)
        self.label_3.setGeometry(QtCore.QRect(180, 470, 101, 31))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Tab1)
        self.label_4.setGeometry(QtCore.QRect(140, 520, 47, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Tab1)
        self.label_5.setGeometry(QtCore.QRect(180, 510, 91, 41))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Tab1)
        self.label_6.setGeometry(QtCore.QRect(480, 330, 231, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Tab1)
        self.label_7.setGeometry(QtCore.QRect(800, 410, 71, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Tab1)
        self.label_8.setGeometry(QtCore.QRect(800, 460, 61, 31))
        self.label_8.setObjectName("label_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 370, 191, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 201, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 0, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.Tab1)
        self.pushButton.setGeometry(QtCore.QRect(790, 360, 171, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.Tab1)
        self.label_9.setGeometry(QtCore.QRect(860, 410, 101, 31))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Tab1)
        self.label_10.setGeometry(QtCore.QRect(860, 460, 101, 31))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Tab1)
        self.label_11.setGeometry(QtCore.QRect(460, 30, 241, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Tab1)
        self.label_12.setGeometry(QtCore.QRect(440, 70, 171, 61))
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.Tab1)
        self.lineEdit.setGeometry(QtCore.QRect(620, 90, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.Tab1)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 130, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_13 = QtWidgets.QLabel(self.Tab1)
        self.label_13.setGeometry(QtCore.QRect(496, 190, 51, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Tab1)
        self.label_14.setGeometry(QtCore.QRect(496, 220, 51, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Tab1)
        self.label_15.setGeometry(QtCore.QRect(496, 240, 51, 51))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Tab1)
        self.label_16.setGeometry(QtCore.QRect(536, 180, 91, 41))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Tab1)
        self.label_17.setGeometry(QtCore.QRect(536, 209, 81, 41))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.Tab1)
        self.label_18.setGeometry(QtCore.QRect(536, 239, 81, 51))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.pushButton_5 = QtWidgets.QPushButton(self.Tab1)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 70, 111, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.Tab1, "")
        self.Tab2 = QtWidgets.QWidget()
        self.Tab2.setObjectName("Tab2")
        self.label_19 = QtWidgets.QLabel(self.Tab2)
        self.label_19.setGeometry(QtCore.QRect(510, 201, 51, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Tab2)
        self.label_20.setGeometry(QtCore.QRect(760, 420, 71, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.Tab2)
        self.label_21.setGeometry(QtCore.QRect(474, 41, 241, 41))
        self.label_21.setObjectName("label_21")
        self.pushButton_3 = QtWidgets.QPushButton(self.Tab2)
        self.pushButton_3.setGeometry(QtCore.QRect(760, 380, 171, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_22 = QtWidgets.QLabel(self.Tab2)
        self.label_22.setGeometry(QtCore.QRect(760, 470, 61, 31))
        self.label_22.setObjectName("label_22")
        self.pushButton_4 = QtWidgets.QPushButton(self.Tab2)
        self.pushButton_4.setGeometry(QtCore.QRect(534, 141, 101, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_23 = QtWidgets.QLabel(self.Tab2)
        self.label_23.setGeometry(QtCore.QRect(454, 81, 171, 61))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Tab2)
        self.label_24.setGeometry(QtCore.QRect(510, 251, 51, 51))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.Tab2)
        self.label_25.setGeometry(QtCore.QRect(100, 390, 231, 61))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.Tab2)
        self.label_26.setGeometry(QtCore.QRect(440, 350, 231, 41))
        self.label_26.setObjectName("label_26")
        self.pushButton_93 = QtWidgets.QPushButton(self.Tab2)
        self.pushButton_93.setGeometry(QtCore.QRect(130, 440, 161, 41))
        self.pushButton_93.setObjectName("pushButton_93")
        self.label_27 = QtWidgets.QLabel(self.Tab2)
        self.label_27.setGeometry(QtCore.QRect(140, 540, 47, 21))
        self.label_27.setObjectName("label_27")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Tab2)
        self.lineEdit_2.setGeometry(QtCore.QRect(634, 101, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_28 = QtWidgets.QLabel(self.Tab2)
        self.label_28.setGeometry(QtCore.QRect(510, 231, 51, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.Tab2)
        self.label_29.setGeometry(QtCore.QRect(140, 490, 31, 31))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.Tab2)
        self.label_30.setGeometry(QtCore.QRect(180, 490, 101, 31))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.Tab2)
        self.label_31.setGeometry(QtCore.QRect(810, 470, 101, 31))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.Tab2)
        self.label_32.setGeometry(QtCore.QRect(180, 530, 91, 41))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.Tab2)
        self.label_33.setGeometry(QtCore.QRect(550, 220, 81, 41))
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.Tab2)
        self.label_34.setGeometry(QtCore.QRect(550, 191, 91, 41))
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.Tab2)
        self.label_35.setGeometry(QtCore.QRect(550, 250, 81, 51))
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.Tab2)
        self.label_36.setGeometry(QtCore.QRect(810, 420, 101, 31))
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Tab2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 190, 441, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_lambda_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_lambda_2.setObjectName("label_lambda_2")
        self.gridLayout_2.addWidget(self.label_lambda_2, 3, 0, 1, 1)
        self.label_phi_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_phi_2.setObjectName("label_phi_2")
        self.gridLayout_2.addWidget(self.label_phi_2, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 1, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 1, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 1, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 0, 0, 1, 4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 2, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 3, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 3, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Tab2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 30, 201, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_42 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_4.addWidget(self.label_42)
        self.radioButton_GRS_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_GRS_4.setObjectName("radioButton_GRS_4")
        self.verticalLayout_4.addWidget(self.radioButton_GRS_4)
        self.radioButton_WGS_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_WGS_4.setObjectName("radioButton_WGS_4")
        self.verticalLayout_4.addWidget(self.radioButton_WGS_4)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Tab2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(450, 390, 201, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_10 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_3.addWidget(self.radioButton_10, 1, 0, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout_3.addWidget(self.radioButton_12, 2, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_3.addWidget(self.radioButton_9, 2, 0, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_3.addWidget(self.radioButton_11, 1, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 0, 0, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.Tab2)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 70, 111, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.Tab2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Interfejs aplikacji geodezyjnej"))
        self.groupBox.setTitle(_translate("Dialog", "Wybór parametrów elipsoidy:"))
        self.radioButton_GRS.setText(_translate("Dialog", "GRS80"))
        self.radioButton_WGS.setText(_translate("Dialog", "WGS84"))
        self.label_phi.setText(_translate("Dialog", "Wprowadzenie szerokości geodezyjnej φ:"))
        self.label_lambda.setText(_translate("Dialog", "Wprowadzenie długości geodezyjnej λ:"))
        self.pushButton_92.setText(_translate("Dialog", "Przelicz współrzędne na XY92"))
        self.label.setText(_translate("Dialog", "Przeliczenie współrzędnych do układu PL-1992:"))
        self.label_2.setText(_translate("Dialog", "X92 ="))
        self.label_4.setText(_translate("Dialog", "Y92 ="))
        self.label_6.setText(_translate("Dialog", "Przeliczenie współrzędnych do układu PL-2000:"))
        self.label_7.setText(_translate("Dialog", "X2000 ="))
        self.label_8.setText(_translate("Dialog", "Y2000 ="))
        self.groupBox_2.setTitle(_translate("Dialog", "Wybór strefy dla układu PL-2000:"))
        self.radioButton_2.setText(_translate("Dialog", "Strefa 7"))
        self.radioButton.setText(_translate("Dialog", "Strefa 5"))
        self.radioButton_3.setText(_translate("Dialog", "Strefa 6"))
        self.radioButton_4.setText(_translate("Dialog", "Strefa 8"))
        self.pushButton.setText(_translate("Dialog", "Przelicz współrzędne na XY2000"))
        self.label_11.setText(_translate("Dialog", "Przeliczenie na współrzędne geocentryczne XYZ:"))
        self.label_12.setText(_translate("Dialog", "Wprowadzenie wysokości H w [m]:"))
        self.pushButton_2.setText(_translate("Dialog", "Przelicz na XYZ"))
        self.label_13.setText(_translate("Dialog", "X ="))
        self.label_14.setText(_translate("Dialog", "Y ="))
        self.label_15.setText(_translate("Dialog", "Z ="))
        self.pushButton_5.setText(_translate("Dialog", "Zatwierdź elipsoide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab1), _translate("Dialog", "Wartości w stopnich dziesiętnych"))
        self.label_19.setText(_translate("Dialog", "X ="))
        self.label_20.setText(_translate("Dialog", "X2000 ="))
        self.label_21.setText(_translate("Dialog", "Przeliczenie na współrzędne geocentryczne XYZ:"))
        self.pushButton_3.setText(_translate("Dialog", "Przelicz współrzędne na XY2000"))
        self.label_22.setText(_translate("Dialog", "Y2000 ="))
        self.pushButton_4.setText(_translate("Dialog", "Przelicz na XYZ"))
        self.label_23.setText(_translate("Dialog", "Wprowadzenie wysokości H w [m]:"))
        self.label_24.setText(_translate("Dialog", "Z ="))
        self.label_25.setText(_translate("Dialog", "Przeliczenie współrzędnych do układu PL-1992:"))
        self.label_26.setText(_translate("Dialog", "Przeliczenie współrzędnych do układu PL-2000:"))
        self.pushButton_93.setText(_translate("Dialog", "Przelicz współrzędne na XY92"))
        self.label_27.setText(_translate("Dialog", "Y92 ="))
        self.label_28.setText(_translate("Dialog", "Y ="))
        self.label_29.setText(_translate("Dialog", "X92 ="))
        self.label_38.setText(_translate("Dialog", "Nazwa współrzędnej"))
        self.label_lambda_2.setText(_translate("Dialog", "Wprowadzenie długości geodezyjnej λ:"))
        self.label_phi_2.setText(_translate("Dialog", "Wprowadzenie szerokości geodezyjnej φ:"))
        self.label_41.setText(_translate("Dialog", "Sekundy"))
        self.label_40.setText(_translate("Dialog", "Stopnie"))
        self.label_39.setText(_translate("Dialog", "Minuty"))
        self.label_37.setText(_translate("Dialog", " Wprowadzenie współrzędnych geodezyjnych"))
        self.label_42.setText(_translate("Dialog", "Wybór elipsoidy"))
        self.radioButton_GRS_4.setText(_translate("Dialog", "GRS80"))
        self.radioButton_WGS_4.setText(_translate("Dialog", "WGS84"))
        self.radioButton_10.setText(_translate("Dialog", "Strefa 5"))
        self.radioButton_12.setText(_translate("Dialog", "Strefa 8"))
        self.radioButton_9.setText(_translate("Dialog", "Strefa 7"))
        self.radioButton_11.setText(_translate("Dialog", "Strefa 6"))
        self.label_43.setText(_translate("Dialog", "Wybór strefy dla układu PL-2000:"))
        self.pushButton_6.setText(_translate("Dialog", "Zatwierdź elipsoide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab2), _translate("Dialog", "Wartości w stopniach, minutach, sekundach"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

